### ISSUE TITLE
JEI support

### ISSUE THREAD

**Issue by Abbie5** [MattiDragon/TlaApi#2]

**Comment by MattiDragon** [comment]
I'll add JEI support once they update to 1.20.6

**Comment by MimzyFang** [comment]
JEI has been updated to 1.21 so that would be something that could be done with the update to that version ^^

https://modrinth.com/mod/jei/version/19.0.0.1

**Comment by Abbie5** [comment]
can this be closed now that 1.2.0 is released which added jei support?
