### ISSUE TITLE
Mark version 1.2.0 of TLA as compatible with 1.21.1

### ISSUE THREAD

**Issue by MimzyFang** [MattiDragon/TlaApi#7]
the 1.2.0 version of TLA was released for 1.21 thoug due to the minimal changes that where made in 1.21.1 it's functionality was not affected by that update and can be marked as compatible with 1.21.1 on modrinth

https://modrinth.com/mod/tla-api/version/1.2.0+mc.1.21

**Comment by MattiDragon** [comment]
Thanks for testing. As the jar already has a compatible dependency, I've simply updated the modrinth listing.
